name: base
description: "Base package"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  dio: 5.3.2
  basic_utils: 5.6.1
  jiffy: 6.3.1
  shared_preferences: 2.2.1
  syncfusion_flutter_datepicker: 27.1.48
  lottie: 3.3.1
  easy_localization: 3.0.7
  photo_view: 0.14.0
  video_player: 2.8.3
  pattern_formatter: 4.0.0
  file_picker: 8.1.7
  image_picker: 1.0.6
  smooth_corner: 1.1.1
  collection: 1.19.0
  dotted_border: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0